import sqlite3
from queries import *
from datetime import datetime
from read_all import *
from tabulate import tabulate
import os
def main():
    os.system('rm -f social.db')
    os.system('sqlite3 social.db < schema.sql')

    db = sqlite3.connect('social.db')
    with db:
        setup_database(db)


    def pretty_print(data, column_names):
        print(tabulate(data, headers=column_names, tablefmt="fancy_grid"))

    data,column_name = recommended_post(db, "frank123")

    pretty_print(data, column_name)

def setup_database(db):
    lis = ["users", "accounts", "follows", "posts", "likes", "comments"]
    get_all(db, lis)

    users = data = [
    ("dave@email.com", "Dave", "Martin"),
    ("emma@email.com", "Emma", "Clark"),
    ("frank@email.com", "Frank", "Harris"),
    ("grace@email.com", "Grace", "Walker"),
    ("henry@email.com", "Henry", "Lopez"),
    ("ivy@email.com", "Ivy", "Taylor"),
    ("jack@email.com", "Jack", "Miller"),
    ("karen@email.com", "Karen", "Wilson"),
    ("luke@email.com", "Luke", "Davis"),
    ("mona@email.com", "Mona", "Smith"),
    ("nathan@email.com", "Nathan", "Brown"),
    ("olivia@email.com", "Olivia", "Johnson"),
    ("paul@email.com", "Paul", "White"),
    ("quinn@email.com", "Quinn", "Adams"),
    ("rachel@email.com", "Rachel", "Lewis"),
    ("sam@email.com", "Sam", "Hall"),
    ("tina@email.com", "Tina", "Allen"),
    ("ursula@email.com", "Ursula", "Young"),
    ("victor@email.com", "Victor", "King"),
    ("wanda@email.com", "Wanda", "Wright"),
    ("xavier@email.com", "Xavier", "Scott"),
    ("yasmin@email.com", "Yasmin", "Green"),
    ("zach@email.com", "Zach", "Baker"),
    ("abigail@email.com", "Abigail", "Moore"),
    ("brandon@email.com", "Brandon", "Evans"),
    ("chloe@email.com", "Chloe", "Murphy"),
    ("daniel@email.com", "Daniel", "Reed"),
    ("ella@email.com", "Ella", "Cook"),
    ("felix@email.com", "Felix", "Rogers"),
    ("georgia@email.com", "Georgia", "Morgan"),
    ("harry@email.com", "Harry", "Bell"),
    ("isla@email.com", "Isla", "Bailey"),
    ("jason@email.com", "Jason", "Rivera"),
    ("kyle@email.com", "Kyle", "Cooper"),
    ("laura@email.com", "Laura", "Richardson"),
    ("matthew@email.com", "Matthew", "Cox"),
    ("nora@email.com", "Nora", "Howard"),
    ("owen@email.com", "Owen", "Ward"),
    ("phoebe@email.com", "Phoebe", "Torres"),
    ("ryan@email.com", "Ryan", "Peterson"),
    ("sophia@email.com", "Sophia", "Gray"),
    ("thomas@email.com", "Thomas", "Ramirez"),
    ("uma@email.com", "Uma", "James"),
    ("vincent@email.com", "Vincent", "Watson"),
    ("willow@email.com", "Willow", "Brooks"),
    ("xena@email.com", "Xena", "Kelly"),
    ("yuri@email.com", "Yuri", "Sanders"),
    ("zoe@email.com", "Zoe", "Price"),
    ("aaron@email.com", "Aaron", "Bennett"),
    ("bella@email.com", "Bella", "Wood"),
    ("caleb@email.com", "Caleb", "Barnes"),
    ("diana@email.com", "Diana", "Ross"),
    ("ethan@email.com", "Ethan", "Henderson"),
    ("fiona@email.com", "Fiona", "Coleman"),
    ("gavin@email.com", "Gavin", "Jenkins"),
    ("hannah@email.com", "Hannah", "Perry"),
    ("ian@email.com", "Ian", "Powell"),
    ("julia@email.com", "Julia", "Long"),
    ("kevin@email.com", "Kevin", "Patterson"),
    ("lily@email.com", "Lily", "Hughes"),
    ("max@email.com", "Max", "Flores"),
    ("nina@email.com", "Nina", "Washington"),
    ("oscar@email.com", "Oscar", "Butler"),
    ("penny@email.com", "Penny", "Simmons"),
    ("quincy@email.com", "Quincy", "Foster"),
    ("rose@email.com", "Rose", "Gonzales"),
    ("sean@email.com", "Sean", "Bryant"),
    ("tara@email.com", "Tara", "Alexander"),
    ("ulric@email.com", "Ulric", "Russell"),
    ("vicky@email.com", "Vicky", "Griffin"),
    ("wayne@email.com", "Wayne", "Diaz"),
    ("xander@email.com", "Xander", "Hayes"),
    ("yasmin2@email.com", "Yasmin", "Myers"),
    ("zane@email.com", "Zane", "Ford"),
    ("amelia@email.com", "Amelia", "Hamilton"),
    ("benjamin@email.com", "Benjamin", "Graham"),
    ("carla@email.com", "Carla", "Sullivan"),
    ("derek@email.com", "Derek", "Wallace"),
    ("eliza@email.com", "Eliza", "Woods"),
    ("freddie@email.com", "Freddie", "Cole"),
    ("gemma@email.com", "Gemma", "West"),
    ("harriet@email.com", "Harriet", "Jordan"),
    ("isaac@email.com", "Isaac", "Owens"),
    ("jessica@email.com", "Jessica", "Reynolds"),
    ("kieran@email.com", "Kieran", "Fisher"),
    ("lucas@email.com", "Lucas", "Ellis"),
    ("madeline@email.com", "Madeline", "Harrison"),
    ("nick@email.com", "Nick", "Gibson"),
    ("oliver@email.com", "Oliver", "McDonald"),
    ("patricia@email.com", "Patricia", "Cruz"),
    ("quentin@email.com", "Quentin", "Marshall"),
    ("ruth@email.com", "Ruth", "Ortiz"),
    ("steven@email.com", "Steven", "Gomez"),
    ("tiffany@email.com", "Tiffany", "Murray"),
    ("ulysses@email.com", "Ulysses", "Freeman"),
    ("vanessa@email.com", "Vanessa", "Wells"),
    ("warren@email.com", "Warren", "Webb"),
    ("xavier2@email.com", "Xavier", "Simpson"),
    ("yasmine@email.com", "Yasmine", "Stevens"),
    ("zara@email.com", "Zara", "Tucker")
]

    
    for email, first_name, last_name in users:
        create_user(db, email, first_name, last_name)
    
    # Create accounts with distinct usernames
    accounts = [
    ("dave987", "dave@email.com"),
    ("emma456", "emma@email.com"),
    ("frank123", "frank@email.com"),
    ("grace789", "grace@email.com"),
    ("henry654", "henry@email.com"),
    ("ivy101", "ivy@email.com"),
    ("jack007", "jack@email.com"),
    ("karen202", "karen@email.com"),
    ("luke333", "luke@email.com"),
    ("mona444", "mona@email.com"),
    ("nathan555", "nathan@email.com"),
    ("olivia999", "olivia@email.com"),
    ("paul111", "paul@email.com"),
    ("quinn222", "quinn@email.com"),
    ("rachel333", "rachel@email.com"),
    ("sam444", "sam@email.com"),
    ("tina555", "tina@email.com"),
    ("ursula666", "ursula@email.com"),
    ("victor777", "victor@email.com"),
    ("wanda888", "wanda@email.com"),
    ("xavier999", "xavier@email.com"),
    ("yasmin000", "yasmin@email.com"),
    ("zach111", "zach@email.com"),
    ("abigail222", "abigail@email.com"),
    ("brandon333", "brandon@email.com"),
    ("chloe444", "chloe@email.com"),
    ("daniel555", "daniel@email.com"),
    ("ella666", "ella@email.com"),
    ("felix777", "felix@email.com"),
    ("georgia888", "georgia@email.com"),
    ("harry999", "harry@email.com"),
    ("isla101", "isla@email.com"),
    ("jason202", "jason@email.com"),
    ("kyle303", "kyle@email.com"),
    ("laura404", "laura@email.com"),
    ("matthew505", "matthew@email.com"),
    ("nora606", "nora@email.com"),
    ("owen707", "owen@email.com"),
    ("phoebe808", "phoebe@email.com"),
    ("ryan909", "ryan@email.com"),
    ("sophia010", "sophia@email.com"),
    ("thomas111", "thomas@email.com"),
    ("uma222", "uma@email.com"),
    ("vincent333", "vincent@email.com"),
    ("willow444", "willow@email.com"),
    ("xena555", "xena@email.com"),
    ("yuri666", "yuri@email.com"),
    ("zoe777", "zoe@email.com"),
    ("aaron888", "aaron@email.com"),
    ("bella999", "bella@email.com"),
    ("caleb101", "caleb@email.com"),
    ("diana202", "diana@email.com"),
    ("ethan303", "ethan@email.com"),
    ("fiona404", "fiona@email.com"),
    ("gavin505", "gavin@email.com"),
    ("hannah606", "hannah@email.com"),
    ("ian707", "ian@email.com"),
    ("julia808", "julia@email.com"),
    ("kevin909", "kevin@email.com"),
    ("lily010", "lily@email.com"),
    ("max111", "max@email.com"),
    ("nina222", "nina@email.com"),
    ("oscar333", "oscar@email.com"),
    ("penny444", "penny@email.com"),
    ("quincy555", "quincy@email.com"),
    ("rose666", "rose@email.com"),
    ("sean777", "sean@email.com"),
    ("tara888", "tara@email.com"),
    ("ulric999", "ulric@email.com"),
    ("vicky101", "vicky@email.com"),
    ("wayne202", "wayne@email.com"),
    ("xander303", "xander@email.com"),
    ("yasmin404", "yasmin2@email.com"),
    ("zane505", "zane@email.com"),
    ("amelia606", "amelia@email.com"),
    ("benjamin707", "benjamin@email.com"),
    ("carla808", "carla@email.com"),
    ("derek909", "derek@email.com"),
    ("eliza010", "eliza@email.com"),
    ("freddie111", "freddie@email.com"),
    ("gemma222", "gemma@email.com"),
    ("harriet333", "harriet@email.com"),
    ("isaac444", "isaac@email.com"),
    ("jessica555", "jessica@email.com"),
    ("kieran666", "kieran@email.com"),
    ("lucas777", "lucas@email.com"),
    ("madeline888", "madeline@email.com"),
    ("nick999", "nick@email.com"),
    ("oliver101", "oliver@email.com"),
    ("patricia202", "patricia@email.com"),
    ("quentin303", "quentin@email.com"),
    ("ruth404", "ruth@email.com"),
    ("steven505", "steven@email.com"),
    ("tiffany606", "tiffany@email.com"),
    ("ulysses707", "ulysses@email.com"),
    ("vanessa808", "vanessa@email.com"),
    ("warren909", "warren@email.com"),
    ("xavier010", "xavier2@email.com"),
    ("yasmine111", "yasmine@email.com"),
    ("zara222", "zara@email.com")
]

    
    for username, email in accounts:
        add_account(db, username, email)
    
    # Create a large number of posts
    posts = [
        ("dave987", "Feeling great today! Dave here."),
        ("emma456", "Excited to start this new journey!"),
        ("frank123", "Just got back from a workout. Feeling strong!"),
        ("grace789", "Can't wait for the weekend!"),
        ("henry654", "Henry checking in. All is well!"),
        ("ivy101", "Exploring the city today, it's a beautiful day!"),
        ("jack007", "Just finished reading an interesting book!"),
        ("karen202", "Had an amazing lunch at a new place."),
        ("luke333", "Busy day at work, but feeling productive."),
        ("mona444", "Looking forward to the weekend getaway."),
        ("nathan555", "Starting a new project today, feeling pumped!"),
        ("olivia999", "Relaxing with some good music and coffee."),
        ("paul111", "Caught a great sunset this evening."),
        ("quinn222", "Working on a coding challenge today."),
        ("rachel333", "Baking cookies this afternoon, smells amazing!"),
        ("sam444", "Just finished watching a fantastic movie."),
        ("tina555", "Taking a break and enjoying the weather."),
        ("ursula666", "Found a new hiking trail, loving the views!"),
        ("victor777", "Reading up on some new tech trends."),
        ("wanda888", "Planning my next vacation adventure."),
        ("xavier999", "Learning a new language, it's tough but fun."),
        ("yasmin000", "Just got a promotion at work!"),
        ("zach111", "Practicing some guitar chords today."),
        ("abigail222", "Meditation really clears the mind."),
        ("brandon333", "Trying out a new recipe tonight."),
        ("chloe444", "Movie marathon kind of day!"),
        ("daniel555", "Hit a new personal record at the gym."),
        ("ella666", "Sketching some new designs."),
        ("felix777", "Back to back meetings all day."),
        ("georgia888", "Caught up on some reading today."),
        ("harry999", "Just finished a puzzle challenge."),
        ("isla101", "Enjoying a peaceful morning walk."),
        ("jason202", "Organizing my workspace today."),
        ("kyle303", "Gaming session with friends tonight!"),
        ("laura404", "Trying out yoga for the first time."),
        ("matthew505", "Planning to build a new PC setup."),
        ("nora606", "Got some amazing news today!"),
        ("owen707", "Late-night brainstorming session."),
        ("phoebe808", "Just completed a big project at work."),
        ("ryan909", "Exploring new photography spots."),
        ("sophia010", "Practicing some calligraphy skills."),
        ("thomas111", "Catching up with old friends today."),
        ("uma222", "Loving this new podcast I discovered."),
        ("vincent333", "Learning how to code a new app."),
        ("willow444", "Nature walk with my dog this morning."),
        ("xena555", "Trying some new workout routines."),
        ("yuri666", "Chilling with some jazz music."),
        ("zoe777", "Weekend movie binge incoming!"),
        ("aaron888", "Fixing up my old bicycle today."),
        ("bella999", "Painting a new canvas, loving the colors."),
        ("caleb101", "Just completed a 5k run!"),
        ("diana202", "Visited a new coffee shop today."),
        ("ethan303", "Finally completed my coding project."),
        ("fiona404", "Relaxing with a good novel."),
        ("gavin505", "Exploring local food markets."),
        ("hannah606", "Backyard BBQ with friends today."),
        ("ian707", "Working on a new coding framework."),
        ("julia808", "Got a new camera, testing it out."),
        ("kevin909", "Revisiting some old favorite songs."),
        ("lily010", "Trying out watercolors for the first time."),
        ("max111", "Late-night gaming marathon."),
        ("nina222", "Going on a road trip tomorrow!"),
        ("oscar333", "New blog post is up!"),
        ("penny444", "Learning some digital art skills."),
        ("quincy555", "Weekend coding sprint."),
        ("rose666", "Visited a museum today, so inspiring."),
        ("sean777", "Sunset photography is the best."),
        ("tara888", "Binge-watching my favorite show."),
        ("ulric999", "Experimenting with new recipes."),
        ("vicky101", "Finished reading a sci-fi novel."),
        ("wayne202", "Tinkering with some DIY electronics."),
        ("xander303", "Caught up on my favorite podcast."),
        ("yasmin404", "Trying out mindfulness meditation."),
        ("zane505", "Just got a new puppy!"),
        ("amelia606", "Started a journal today."),
        ("benjamin707", "Exploring retro video games."),
        ("carla808", "Learning some advanced CSS techniques."),
        ("derek909", "Morning jog in the park."),
        ("eliza010", "Baking bread for the first time."),
        ("freddie111", "Playing some classic board games."),
        ("gemma222", "Practicing my piano skills."),
        ("harriet333", "Reading up on history today."),
        ("isaac444", "Learning how to edit videos."),
        ("jessica555", "Trying some new smoothie recipes."),
        ("kieran666", "Painting a mural today."),
        ("lucas777", "Writing some short stories."),
        ("madeline888", "Practicing yoga and meditation."),
        ("nick999", "Playing basketball at the park."),
        ("oliver101", "Watching some nature documentaries."),
        ("patricia202", "Exploring VR games."),
        ("quentin303", "Started learning guitar."),
        ("ruth404", "Visited a botanical garden today."),
        ("steven505", "Organizing my music playlist."),
        ("tiffany606", "Practicing some sketch art."),
        ("ulysses707", "Late-night coding session."),
        ("vanessa808", "Exploring new hiking trails."),
        ("warren909", "Built a small Raspberry Pi project."),
        ("xavier010", "Just got a new phone, setting it up."),
        ("yasmine111", "Watching an old favorite movie."),
        ("zara222", "Learning new photo editing tricks."),
        ("dave987", "Back at the gym, feeling motivated!"),
        ("emma456", "Learning Python, it's going well so far."),
        ("frank123", "Grabbing some lunch with friends."),
        ("grace789", "Cleaning the house, productive day."),
        ("henry654", "Trying out a new photography lens."),
        ("ivy101", "Relaxing with some tea and a good book."),
        ("jack007", "Built a new website for a client."),
        ("karen202", "Enjoying a beautiful sunset hike."),
        ("luke333", "Late-night coding grind."),
        ("mona444", "New favorite show discovered."),
        ("nathan555", "Trying out a different workout routine."),
        ("olivia999", "Planning a summer getaway."),
        ("paul111", "Listening to some classic rock tunes."),
        ("quinn222", "Practicing front-end development today."),
        ("rachel333", "Cooked a delicious homemade pizza."),
        ("sam444", "Trying my hand at writing poetry."),
        ("tina555", "New yoga poses learned today."),
        ("ursula666", "Reading up on space exploration."),
        ("victor777", "Starting a new video editing project."),
        ("wanda888", "DIY home decor project in progress."),
        ("xavier999", "Just updated my resume."),
        ("yasmin000", "Weekend road trip vibes."),
        ("zach111", "New hiking boots breaking in!"),
        ("abigail222", "Decorating the living room today."),
        ("brandon333", "Listening to a new audiobook."),
        ("chloe444", "Getting into mindfulness journaling."),
        ("daniel555", "Trying intermittent fasting."),
        ("ella666", "Planting a small herb garden."),
        ("felix777", "Coding a chatbot in Python."),
        ("georgia888", "Sketching some logo ideas."),
        ("harry999", "Exploring abandoned places for photography."),
        ("isla101", "Reading a mystery novel."),
        ("jason202", "Attending a virtual tech conference."),
        ("kyle303", "Practicing some 3D modeling today."),
        ("laura404", "Learning about blockchain tech."),
        ("matthew505", "Refurbishing an old computer."),
        ("nora606", "Making homemade candles."),
        ("owen707", "Tried indoor rock climbing for the first time."),
        ("phoebe808", "Listening to some indie bands."),
        ("ryan909", "Working on my personal portfolio website."),
        ("sophia010", "Trying out time-lapse photography."),
        ("thomas111", "Attending a webinar on AI."),
        ("uma222", "Experimenting with latte art."),
        ("vincent333", "New coding project, excited to start."),
        ("willow444", "Starting a travel vlog soon."),
        ("xena555", "Practicing aerial yoga."),
        ("yuri666", "New recipe experiment: vegan brownies."),
        ("zoe777", "Weekend hiking adventure planned."),
    ]

    
    for username, message in posts:
        create_post(db, username, message, datetime.now().isoformat())
    
    # Get post IDs
    posts = db.execute("SELECT * FROM posts").fetchall()
    
    # Create comments (make sure they're unique)
    comments = [
        (posts[0][0], "frank123", "Nice post, Dave!"),
        (posts[1][0], "grace789", "I can relate, Emma!"),
        (posts[2][0], "ivy101", "Great job, Frank!"),
        (posts[3][0], "henry654", "Weekend vibes, Grace!"),
        (posts[4][0], "jack007", "Keep it up, Henry!"),
        (posts[5][0], "karen202", "Love your energy, Ivy!"),
        (posts[6][0], "luke333", "Interesting book, Jack!"),
        (posts[7][0], "mona444", "Lunch sounds amazing, Karen!"),
        (posts[8][0], "dave987", "Productivity is key, Luke!"),
        (posts[9][0], "emma456", "Weekend getaway sounds fun, Mona!"),
        (posts[10][0], "nathan555", "Good luck with your new project!"),
        (posts[11][0], "olivia999", "That sounds relaxing!"),
        (posts[12][0], "paul111", "Nice shot of the sunset!"),
        (posts[13][0], "quinn222", "Coding challenges are fun!"),
        (posts[14][0], "rachel333", "I can almost smell those cookies!"),
        (posts[15][0], "sam444", "What movie did you watch?"),
        (posts[16][0], "tina555", "Enjoy the nice weather!"),
        (posts[17][0], "ursula666", "Hiking sounds like a great idea!"),
        (posts[18][0], "victor777", "Which trends caught your eye?"),
        (posts[19][0], "wanda888", "Let me know where you plan to go!"),
        (posts[20][0], "xavier999", "Which language are you learning?"),
        (posts[21][0], "yasmin000", "Congrats on your promotion!"),
        (posts[22][0], "zach111", "Practice makes perfect!"),
        (posts[23][0], "abigail222", "Meditation is life-changing!"),
        (posts[24][0], "brandon333", "Let us know how the recipe goes!"),
        (posts[25][0], "chloe444", "Perfect day for movies!"),
        (posts[26][0], "daniel555", "Amazing workout achievement!"),
        (posts[27][0], "ella666", "Would love to see your sketches!"),
        (posts[28][0], "felix777", "Busy days ahead, stay strong!"),
        (posts[29][0], "georgia888", "What book are you reading?"),
        (posts[30][0], "harry999", "Puzzles are always fun!"),
        (posts[31][0], "isla101", "Sounds so peaceful."),
        (posts[32][0], "jason202", "Organizing always feels good."),
        (posts[33][0], "kyle303", "What's your favorite game?"),
        (posts[34][0], "laura404", "Yoga is great for relaxation!"),
        (posts[35][0], "matthew505", "Show us your PC build!"),
        (posts[36][0], "nora606", "That's awesome news!"),
        (posts[37][0], "owen707", "Brainstorm sessions are powerful!"),
        (posts[38][0], "phoebe808", "Congratulations on finishing!"),
        (posts[39][0], "ryan909", "Where's your favorite photography spot?"),
        (posts[40][0], "sophia010", "Calligraphy is an art!"),
        (posts[41][0], "thomas111", "Old friends are the best!"),
        (posts[42][0], "uma222", "I'll have to check that out."),
        (posts[43][0], "vincent333", "Good luck coding your app!"),
        (posts[44][0], "willow444", "Nature walks are refreshing!"),
        (posts[45][0], "xena555", "What workouts are you doing?"),
        (posts[46][0], "yuri666", "Jazz always hits differently."),
        (posts[47][0], "zoe777", "Enjoy the movie binge!"),
        (posts[48][0], "aaron888", "Good luck fixing the bike!"),
        (posts[49][0], "bella999", "Your painting must be beautiful!"),
        (posts[50][0], "caleb101", "Congrats on finishing the run!"),
        (posts[51][0], "diana202", "Which coffee shop did you visit?"),
        (posts[52][0], "ethan303", "Great job completing the project!"),
        (posts[53][0], "fiona404", "What novel are you reading?"),
        (posts[54][0], "gavin505", "Local markets are hidden gems!"),
        (posts[55][0], "hannah606", "BBQs are always fun!"),
        (posts[56][0], "ian707", "What framework are you using?"),
        (posts[57][0], "julia808", "Show us some test shots!"),
        (posts[58][0], "kevin909", "Classic songs hit differently."),
        (posts[59][0], "lily010", "Watercolors are tricky but fun!"),
        (posts[60][0], "max111", "What games are you playing?"),
        (posts[61][0], "nina222", "Enjoy your road trip!"),
        (posts[62][0], "oscar333", "Link to your blog?"),
        (posts[63][0], "penny444", "Digital art is challenging!"),
        (posts[64][0], "quincy555", "Good luck with the sprint!"),
        (posts[65][0], "rose666", "Museums are so inspiring!"),
        (posts[66][0], "sean777", "Sunset photos are magical."),
        (posts[67][0], "tara888", "What show are you watching?"),
        (posts[68][0], "ulric999", "What recipe did you try?"),
        (posts[69][0], "vicky101", "Sci-fi novels are the best!"),
        (posts[70][0], "wayne202", "DIY projects are fun!"),
        (posts[71][0], "xander303", "Which podcast do you recommend?"),
        (posts[72][0], "yasmin404", "Meditation is peaceful."),
        (posts[73][0], "zane505", "Congrats on the new puppy!"),
        (posts[74][0], "amelia606", "Journaling is so therapeutic!"),
        (posts[75][0], "benjamin707", "Retro games are classic!"),
        (posts[76][0], "carla808", "Advanced CSS is powerful!"),
        (posts[77][0], "derek909", "Morning jogs are refreshing."),
        (posts[78][0], "eliza010", "I love baking too!"),
        (posts[79][0], "freddie111", "What board games did you play?"),
        (posts[80][0], "gemma222", "Piano practice is soothing!"),
        (posts[81][0], "harriet333", "History can be fascinating."),
        (posts[82][0], "isaac444", "Video editing is fun!"),
        (posts[83][0], "jessica555", "Smoothies are healthy and delicious!"),
        (posts[84][0], "kieran666", "Mural painting sounds amazing!"),
        (posts[85][0], "lucas777", "Short stories are powerful."),
        (posts[86][0], "madeline888", "Yoga helps with focus."),
        (posts[87][0], "nick999", "Basketball is a great workout!"),
        (posts[88][0], "oliver101", "Nature documentaries are calming."),
        (posts[89][0], "patricia202", "VR games are the future!"),
        (posts[90][0], "quentin303", "Good luck with the guitar!"),
        (posts[91][0], "ruth404", "Botanical gardens are beautiful!"),
        (posts[92][0], "steven505", "I need to update my playlist too."),
        (posts[93][0], "tiffany606", "Sketching is relaxing."),
        (posts[94][0], "ulysses707", "Night coding is productive!"),
        (posts[95][0], "vanessa808", "Hiking is always refreshing!"),
        (posts[96][0], "warren909", "Raspberry Pi projects are fun!"),
        (posts[97][0], "xavier010", "New phone setups are fun!"),
        (posts[98][0], "yasmine111", "What movie are you watching?"),
        (posts[99][0], "zara222", "Photo editing is an art!")
    ]

    
    for post_id, username, message in comments:
        create_comment(db, post_id, username, message, datetime.now().isoformat())
    
    # Create likes (distinct users liking posts)
    likes = [
        ("frank123", posts[0][0]),
        ("frank123", posts[3][0]),
        ("grace789", posts[1][0]),
        ("ivy101", posts[2][0]),
        ("jack007", posts[3][0]),
        ("henry654", posts[4][0]),
        ("karen202", posts[5][0]),
        ("luke333", posts[6][0]),
        ("mona444", posts[7][0]),
        ("dave987", posts[8][0]),
        ("emma456", posts[9][0])

    ]
    
    for username, post_id in likes:
        create_like(db, username, post_id)
    
    # Create follows (distinct user follow relationships)
    follows = [
        ("frank123", "dave987"),
        ("grace789", "emma456"),
        ("ivy101", "frank123"),
        ("jack007", "grace789"),
        ("henry654", "ivy101"),
        ("karen202", "jack007"),
        ("luke333", "henry654"),
        ("mona444", "karen202"),
        ("dave987", "luke333"),
        ("emma456", "mona444"),
        ("frank123", "grace789"),
        ("grace789", "ivy101"),
        ("ivy101", "jack007"),
        ("jack007", "henry654"),
        ("henry654", "karen202"),
        ("karen202", "luke333"),
        ("luke333", "mona444"),
        ("mona444", "dave987"),
        ("dave987", "emma456")
    ]
    
    for follower, followee in follows:
        create_follow(db, follower, followee)






if __name__ == "__main__":
    main()
    # pass
